#!/bin/bash

[ -e /etc/krb5.d/kutils.conf ] && source /etc/krb5.d/kutils.conf

function usage {
        echo "Usage: `basename $0` [-k <keytab:/etc/krb5.keytab>] [-R <REALM>] [-p <policy>]"
}

required=0
required_provided=0

hostname=$(hostname)
keytab="/etc/krb5.keytab"
#realm=$(grep "default_realm" /etc/krb5.conf | awk -F= '{print $2}' | sed -e 's/^ //')

while getopts "s:k:R:p:h" option;
do
        case ${option} in
        k) #Optional: Alternative keytab file
                keytab=${OPTARG}
        ;;
        R) #Optional: Defined Realm
                realm=`echo ${OPTARG} | tr a-z A-Z`
        ;;
        p) #Optional: User defined policy
                policy=${OPTARG}
        ;;
        h)
                usage;
                exit 0;
        ;;
        *)
                usage;
                exit 1;
        esac;
done

if [ ${required_provided} -lt ${required} ]; then
        usage;
        exit 1;
fi;

fqdnLC=`echo ${hostname} | tr A-Z a-z`
fqdnUC=`echo ${hostname} | tr a-z A-Z`
hostnameLC=`echo ${hostname} | awk -F. '{print $1}' | tr A-Z a-z`
hostnameUC=`echo ${hostnameLC} | tr a-z A-Z`

for s in "host" "HOST";
do
	# Removing upper first, since nothing seems to actually use it.
	# "host/${hostnameLC^}"
	for h in "${fqdnLC}" "${fqdnUC}" "${hostnameLC}" "${hostnameUC}";
	do
		princ="${s}/${p}"
		[ -n "${realm}" ] && princ="${princ}@${realm}"
		${basedir}/kaddprinc -u "${princ}" -o "-randkey -policy ${policy:-${defaultHostPolicy}}"
		${basedir}/kaddkeytab -u "${princ}" -k "${keytab}"
	done
done

#Windows host look up looks for service accounts so we need to generate them too
for srvhost in "${hostnameLC}\$" "${hostnameUC}\$";
do
	[ -n "${realm}" ] && srvhost="${srvhost}@${realm}"
        ${basedir}/kaddprinc -u "${srvhost}" -o "-randkey -policy ${policy:-${defaultHostPolicy}}"
        ${basedir}/kaddkeytab -u "${srvhost}" -k ${keytab}
done

